# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todoFb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for todoFb
  pod 'Firebase/Core'
  #target 'todoFb-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  #target 'todoFbTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

end

#target 'todoFb-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for todoFb-tvOS

  #target 'todoFb-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

#end
